"""
Export web-viewer GLB assets from the built shoulder scene.

Two GLB files, both in the same coordinate space so the shoulder sits inside the
body:

  shoulder-atlas.glb  the 42 non-skin shoulder structures
  body-context.glb    BodyParts3D's whole-body Skin mesh

THIS SCRIPT WRITES NO MANIFEST, AND THAT IS THE POINT.

It used to. It wrote one to assets/anatomy/generated/shoulder/right/manifest.json,
which is the CANONICAL asset contract -- the document that records which asi:*
structures the product claims, on which source mesh, with which laterality. The
viewer needed a different document, so it wrote one over the top of the canonical
file. That silently destroyed it, and the 12 laterality tests that read real builds
as their evidence failed with "entries is not iterable". They were right.

Now:
  - geometry goes to assets/anatomy/atlas/shoulder/right/
  - the atlas manifest is generated by scripts/build-atlas-manifest.mjs from the
    canonical manifest plus the reviewed system map, and refuses to write here
  - the canonical manifest is written only by scripts/build-anatomy.mjs

Deliberately exported WITHOUT materials. The tissue system is PRESENTATION
metadata and must not be baked into the asset where it would read as anatomical
identity. The viewer assigns materials at load time from the reviewed
anatomy-system-map, via a tested TypeScript module, so the same geometry can be
re-presented without re-exporting. This also keeps the files smaller.

BodyParts3D 4.0 is CC BY 4.0: attribution travels with the asset and is recorded in
the atlas manifest, not implied by the file.

Run: blender --background shoulder.blend --python export-web-glb.py
"""

import bpy
import json
import os
import shutil

REPO = r"E:\1project\asi-atlas-v2"
SPIKE = os.path.join(REPO, "spikes", "shoulder-geometry")
# assets/anatomy/atlas/ is the atlas's own tracked home; apps/web/public/anatomy/ is
# what the web app actually serves. NEVER assets/anatomy/generated/: that tree is
# owned by the canonical anatomy pipeline and this script has no business in it.
ATLAS = os.path.join(REPO, "assets", "anatomy", "atlas", "shoulder", "right")
PUBLIC = os.path.join(REPO, "apps", "web", "public", "anatomy", "atlas", "shoulder", "right")
CANONICAL_MANIFEST = os.path.join(REPO, "assets", "anatomy", "generated", "shoulder", "right", "manifest.json")
os.makedirs(ATLAS, exist_ok=True)
os.makedirs(PUBLIC, exist_ok=True)


def refuse_canonical_write(path):
    """Fail loudly rather than write into the canonical tree.

    Checked at every write site. A generator that has already overwritten the
    canonical manifest has already done the damage, so this has to run first.
    """
    norm = os.path.normpath(path).replace("\\", "/")
    if "/anatomy/generated/" in norm:
        raise RuntimeError(
            f"[X] refusing to write into the canonical anatomy tree: {norm}\n"
            "    The canonical manifest is the domain/evidence product and is owned by\n"
            "    scripts/build-anatomy.mjs. Atlas artifacts belong under assets/anatomy/atlas/."
        )


with open(os.path.join(REPO, "assets", "anatomy", "generated", "shoulder-scene.json"),
          encoding="utf-8") as fh:
    SCENE = json.load(fh)
sys_of = {s["id"]: s["system"] for s in SCENE["structures"]}
label_of = {s["id"]: s["label"] for s in SCENE["structures"]}
SYS_OF = sys_of
LABEL_OF = label_of

skin = [o for o in bpy.data.objects if o.type == "MESH" and sys_of.get(o.name) == "skin"]
shoulder = [o for o in bpy.data.objects
            if o.type == "MESH" and sys_of.get(o.name) not in (None, "skin")]
print(f"[X] skin meshes {len(skin)}  shoulder meshes {len(shoulder)}")


def export(objects, path, label):
    for o in bpy.data.objects:
        if o.type == "MESH":
            o.hide_render = True
    for o in objects:
        o.hide_render = False
    for o in bpy.data.objects:
        o.select_set(False)
    for o in objects:
        o.select_set(True)
    bpy.context.view_layer.objects.active = objects[0]

    # Identity travels in custom properties, not in the node NAME.
    #
    # three.js sanitises node names: PropertyBinding.sanitizeNodeName replaces
    # [ . : / ] and whitespace with "_", so a node exported as "bp3d:FJ3384"
    # arrives in the browser as "bp3d_FJ3384". A viewer that keys off the name
    # then matches nothing, silently renders every mesh with the glTF default
    # white material, and cannot hide or show anything. Custom properties export
    # to glTF `extras` and arrive as userData untouched.
    #
    # The name is still written, with a sanitised-safe form, because a name is
    # what a human reads in a debugger.
    for o in objects:
        sid = o.name
        o["asi_id"] = sid
        o["asi_label"] = LABEL_OF.get(sid, sid)
        o["asi_system"] = SYS_OF.get(sid, "UNKNOWN")
        o.name = sid.replace(":", "_")

    bpy.ops.export_scene.gltf(
        filepath=path,
        export_format="GLB",
        use_selection=True,
        export_apply=True,
        export_materials="NONE",     # presentation stays in code
        export_yup=True,             # glTF convention; the viewer converts back
        export_texcoords=False,
        export_normals=True,
        export_extras=True,          # carries asi_id / asi_label / asi_system
    )

    # Put the original names back so a re-save of this .blend is not confusing.
    for o in objects:
        if "asi_id" in o:
            o.name = o["asi_id"]

    size = os.path.getsize(path)
    tris = 0
    for o in objects:
        if o.type == "MESH":
            tris += sum(max(0, len(p.vertices) - 2) for p in o.data.polygons)
    print(f"[X] {label:16s} -> {os.path.basename(path)}  objects={len(objects)}  "
          f"tris={tris}  bytes={size} ({size/1024/1024:.2f} MB)")
    return {"file": os.path.basename(path), "objects": len(objects),
            "triangles": tris, "bytes": size}



# ---------------------------------------------------------------- geometry only
#
# Everything below used to build a viewer manifest and write it to
# assets/anatomy/generated/shoulder/right/manifest.json, overwriting the canonical
# asset contract. The atlas manifest is now generated by
# scripts/build-atlas-manifest.mjs from the canonical manifest and the reviewed
# system map, so this script contributes geometry and nothing else.

atlas_stats = export(shoulder, os.path.join(ATLAS, "shoulder-atlas.glb"), "shoulder-atlas")
export(skin, os.path.join(ATLAS, "body-context.glb"), "body-context")

for name in ("shoulder-atlas.glb", "body-context.glb"):
    refuse_canonical_write(os.path.join(ATLAS, name))
    src = os.path.join(ATLAS, name)
    dst = os.path.join(PUBLIC, name)
    shutil.copy2(src, dst)
    print(f"[X] published {name} -> apps/web/public/anatomy/atlas/shoulder/right/ "
          f"({os.path.getsize(dst)} bytes)")

# The canonical manifest must exist and must still be the canonical contract. If it
# has been replaced by something else, say so now rather than after a viewer has
# been built against the wrong document.
with open(CANONICAL_MANIFEST, encoding="utf-8") as fh:
    canon = json.load(fh)
if "entries" not in canon or "regions" not in canon:
    raise RuntimeError(
        "[X] " + CANONICAL_MANIFEST + " does not look like a canonical AssetManifest "
        "(missing `entries` or `regions`). The atlas export must never leave that file "
        "in a viewer-shaped state."
    )
print(f"[X] canonical manifest intact: {len(canon['entries'])} entries, regions={canon['regions']}")
print("[X] next: node scripts/build-atlas-manifest.mjs --region shoulder --side right")
print("[X] DONE")